eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
      
server:
  port: 9006
  
  
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'