eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:  
#    ip-address: 10.0.1.32
    prefer-ip-address: true
       
server:
#  port: 9001
  port: ${PORT:${SERVER_PORT:0}}
  
sujeitos: Eu, Voce, Ele, Ela, Nos
