server:
  port: 8090
  
eureka: 
   client:
     register-with-eureka: false
     fetch-registry: false   
#     service-url: http://localhost:8091/eureka, http://localhost:8092/eureka
       
   instance:
     status-page-url-path: $(management.context Path}/info 
     health-check-url-path: $(management.contextPath/health 
     hostname: localhost 
 
